### PR TITLE
Reduce memory use by never loading file into memory

### PR DESCRIPTION
**Pull request by alexschrod**
Instead, hash it in chunks and uploading it in a streaming fashion

### CODE REVIEW

**Comment by alexschrod** [comment]
This will fix issue #17, at least the part about the memory consumption.

**Comment by HazCod** [comment]
Please merge this @havardgulldahl , this is a much needed feature. THank you @alexschrod.

**Comment by alexschrod** [comment]
I'm sure @havardgulldahl is just busy with "real life" or something. :)

In the meantime, it's not particularly difficult to install manually, just check out my fork and run `pip install -r requirements.txt` in the root folder.

**Comment by HazCod** [comment]
Sure, but it keeps the regular folks from using your good juice. :+1:

**Comment by cowai** [comment]
@alexschrod Your patch will not apply to jottacloudclient right? I installed your version and after that installed jottacloudclient (pip install jottacloudclient) but I get the same error with files bigger than ram still.

**Comment by havardgulldahl** [comment]
Sorry about the lag, guys. I'll get to it shortly. 

Sendt fra min mobiltelefon

**Comment by HazCod** [comment]
Thank you @havardgulldahl

**Pull request merged**
