### PR TITLE
Fixes #59, prune flags for ability delete remote content missing locally.

### LINKED ISSUE #59: Folders only existing at jotta is not deleted. Same goes for files inside those folders.
If I sync a folder to jotta, and then deletes it locally will make it stay undeleted at jotta forever. Is this intended?

### PR DESCRIPTION
**Pull request by cowai**
Hi,
This introduces --prune-files, --prune-folders and --prune-all (for files and folders).
The old default behaviour was deleting files but not folders. Now the default is no deletion without the corresponding prune flag.

### CODE REVIEW

**Comment by havardgulldahl** [comment]
Great stuff, thanks, @cowai!

**Comment by cowai** [comment]
Hey thanks for the merge!
We probably should mention this in the changelog. 0.4.1 is labeled a bug fix but really also introduced new flags and changed default behaviour. It should be mentioned I think.

**Comment by havardgulldahl** [comment]
You're quite right of course. It's too late for the   `0.4.1` release, but the `0.4.2 ` and `master` branches document the new behaviour. 

We should also have something in the wiki about this. Are you able write something up?

**Comment by cowai** [comment]
Yes I can write up something when I have time. Maybe tonight:)

**Pull request merged**
